### ISSUE TITLE
Bugs with and without `-c`, there is something for everybody!

### ISSUE THREAD

**Issue by fgeorgatos** [sfranky/qtop#52]
```
[gef@ui01 qtop]$ ./qtop.py -s /home/gef/arena/qtop-sge2/results/gef_J70JeQFSYYOW9jDg6XfxzQ -c
PBS report tool. All bugs added by sfranky@gmail.com. Cross fingers now...
Please try: watch -d + /home/gef/arena/qtop-sge3/qtop/qtop.py -s /home/gef/arena/qtop-sge2/results/gef_J70JeQFSYYOW9jDg6XfxzQ

===> Job accounting summary <=== (Rev: 3000 $) 2015-09-25 17:23:30.798377 WORKDIR = /home/gef/arena/qtop-sge3/qtop
Usage Totals:   17/17    Nodes | 61/408  Cores |   61+30 jobs (R + Q) reported by qstat -q
Queues: |  alice: 60 | biomed: 1 | cta: 0 | ctaprod: 0 | drihm: 0 | dteam.cg: 0 | gisela.cg: 0 | ibchem.cg: 0 | ibearth.cg: 0 | ibeng.cg: 0 | iber.cg: 0 | ibhpc.cg: 0 | ibict.cg: 0 | iblife.cg: 0 | ibops.cg: 0 | ibphys.cg: 0 | ibsocial.cg: 0 | ibtut.cg: 0 | ops.cg: 0 | sqm.test: 0 | Pending: 0 + 30| * implies blocked

===> Worker Nodes occupancy <=== (you can read vertically the node IDs; nodes in free state are noted with - )
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111111111111111111111111111111111111111111111111111111111111111={_Worker_}
000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999000000000011111111112222222222333333333344444444445555555555666666={__Node__}
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345={___ID___}
Traceback (most recent call last):
  File "./qtop.py", line 1022, in <module>
    _func(*args)
  File "./qtop.py", line 749, in display_wn_occupancy
    display_selected_occupancy_parts(print_char_start, print_char_stop, wn_vert_labels, core_user_map, pattern_of_id, workernodes_occupancy)
  File "./qtop.py", line 589, in display_selected_occupancy_parts
    fn(*args, **kwargs)
  File "./qtop.py", line 601, in print_single_attr_line
    attr_line = insert_separators(line, SEPARATOR, options.WN_COLON) + '={}'.format(label)
ValueError: zero length field name in format
[gef@ui01 qtop]$
[gef@ui01 qtop]$ ./qtop.py -s /home/gef/arena/qtop-sge2/results/gef_J70JeQFSYYOW9jDg6XfxzQ
PBS report tool. All bugs added by sfranky@gmail.com. Cross fingers now...
Please try: watch -d + /home/gef/arena/qtop-sge3/qtop/qtop.py -s /home/gef/arena/qtop-sge2/results/gef_J70JeQFSYYOW9jDg6XfxzQ

Traceback (most recent call last):
  File "./qtop.py", line 1022, in <module>
    _func(*args)
  File "./qtop.py", line 208, in display_job_accounting_summary
    print colorize('===> ', '#') + colorize('Job accounting summary', 'Normal') + colorize(' <=== ', '#') + colorize(
  File "./qtop.py", line 75, in colorize
    if ((not options.NOCOLOR) and pattern != 'account_not_coloured' and text != ' ') else text
ValueError: zero length field name in format
[gef@ui01 qtop]$
```

**Comment by sfranky** [comment]
this is due to python 2.6 not accepting the "{}".format(var) without a positional argument (i.e. "{0}".format(var).
fixed!
