### ISSUE TITLE
vertical stabilizer detached from the airplane...

### ISSUE THREAD

**Issue by fgeorgatos** [sfranky/qtop#78]
```
                                                                  Decided Remapping: True
INFO - DISPLAY AREA
ERROR - Uncaught exception
Traceback (most recent call last):
  File "./qtop.py", line 1412, in <module>
    display_func(*args) if not sections_off[idx] else None
  File "./qtop.py", line 860, in display_wn_occupancy
    display_matrix(workernodes_occupancy)
  File "./qtop.py", line 616, in display_matrix
    fn(*args, **kwargs)
  File "./qtop.py", line 496, in display_wnid_lines
    color_func=highlight_alternately, args=(ALT_LABEL_HIGHLIGHT_COLORS))
  File "./qtop.py", line 507, in print_wnid_lines
    wn_id_str = insert_separators(d[line_nr][start:stop], SEPARATOR, config['vertical_separator_every_X_columns'])
KeyError: 'vertical_separator_every_X_columns'

```

**Comment by sfranky** [comment]
fixed in latest branch (bugfixes)
